### ISSUE TITLE
Exception when inserting new record on empty rowset

### ISSUE THREAD

**Issue by bpangburn** [bpangburn/swingset#95]
If a user has a screen based on an empty rowset, when they try to add a record, the SSDataNavigator attempts to autosave with a call to private method commitChanges(). @prasanthreddy-git  proposed the following fix:

```
			if (rowSet.getRow() > 0) {
				doUpdateRow();
			} 
```

**Comment by errael** [comment]
I wonder which exception was thrown, and from where. Javadoc for updateRow doesn't explicitly call out this case as an exception; but then again can't update a row that doesn't exist so probably a javadoc deficiency.

Interesting to note that with a smart NavBar implementation, this wouldn't be called since nothing is dirty. At least that's what would be expected.
